version: '3'
services:
  app:
    build: ./build/docker
    ports:
      - 8080
    volumes:
      - .:/app
    environment:
      VIRTUAL_HOST: "bobsbest.dev"
    working_dir: /app
    network_mode: "bridge"
    container_name: pestcontrol

